apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-server
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.19.4
      resources:
        limits:
          memory: "256Mi"
          cpu: "100m"
        requests:
          memory: "256Mi"
          cpu: "100m"
      ports:
        - containerPort: 80
