apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      version: "1.0"
  template:
    metadata:
      labels:
        version: "1.0"
    spec:
      containers:
        - name: blue
          image: vamsijakkula/hello-blue-whale:v1
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      version: "2.0"
  template:
    metadata:
      labels:
        version: "2.0"
    spec:
      containers:
        - name: green
          image: vamsijakkula/hello-green-whale:v1
          ports:
            - containerPort: 80
